name: Build Azure Function
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "This is running on branch ${{ github.head_ref }}"
      - run: zip -r azureFn-${{ GITHUB_HEAD_REF }}.zip EHTrigger/ dist/ node_modules .funcignore package.json package-lock.json LICENCE NOTICE host.json README.md
      - uses: actions/upload-artifact@v2
        with:
          name: azureFn-${{ GITHUB_HEAD_REF }}.zip
          path: ./azureFn-${{ GITHUB_HEAD_REF }}.zip